on: push
name: 🚀 Deploy website on push
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ${{ secrets.HOST }}
        ftp-username: ${{ secrets.USERNAME }}
        ftp-password: ${{ secrets.PASSWORD }}