on: push
name: 🚀 Deploy to main server
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME2 }}
        password: ${{ secrets.PASSWORD2 }}
        server-dir: ./wasabistats/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.idea*
          **/.idea*/**
        timeout: 180000
